version: "3.0"

services:

  mysql:
    image: mysql:8.0.29
    environment:
        MYSQL_ROOT_PASSWORD: 'password'
        MYSQL_DATABASE: 'TestDB'
    ports:
      - 3306:3306
    network_mode: host


  mktdata:
    build:
        context: ./
        dockerfile: ./mktdata/Dockerfile
    command: python3 mktdata.py
    #command: python3 ./mktdata/mktdata.py
    ports:
      - 1234:1234
    network_mode: host
    depends_on:
      - mysql


  mysql_client:
    build:
        context: ./
        dockerfile: ./mysql_client/Dockerfile
    command: python3 mysql_client.py
    #command: python3 ./mysql_client/mysql_client.py
    network_mode: host
    depends_on:
      - mktdata
      - mysql

  grafana:
    #image: grafana/grafana:8.2.6
    image: grafana/grafana:8.5.4-ubuntu
    environment:
        GF_PATHS_DATA: '/var/lib/grafana'
    #volumes:
        #- ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
    network_mode: host
    depends_on:
      - mktdata
      - mysql
      - mysql_client

  jupyter:
    build:
        context: ./
        dockerfile: ./jupyter/Dockerfile
    #image: bitnami/jupyter-base-notebook:2.3.0
    environment:
        NB_USER: 'binu'
        CHOWN_HOME: 'yes'
        CHOWN_EXTRA_OPTS: '-R'
        #JUPYTER_TOKEN: 'letmein'
    ports:
      - 8888:8888
    hostname: localhost
    network_mode: host
    volumes:
        - ./jupyter/notebooks:/home/binu
    #-p 8888:8888 --hostname localhost -e NB_USER=binu -e CHOWN_HOME=yes -e CHOWN_EXTRA_OPTS='-R' --user root -w /home/binu/ -v $PWD/work:/home/binu  jup_img
    depends_on:
      - mktdata
      - mysql
      - mysql_client

