version: "3"

services:

  mysql:
    image: mysql:8.0.29
    environment:
        MYSQL_ROOT_PASSWORD: 'password'
        MYSQL_DATABASE: 'TestDB'
    ports:
      - 3306:3306
    network_mode: host


  mktdata:
    build:
        context: ./
        dockerfile: ./mktdata/Dockerfile
    command: python3 mktdata.py
    #command: python3 ./mktdata/mktdata.py
    ports:
      - 1234:1234
    network_mode: host
    depends_on:
      - mysql


  mysql_client:
    build:
        context: ./
        dockerfile: ./mysql_client/Dockerfile
    command: python3 mysql_client.py
    #command: python3 ./mysql_client/mysql_client.py
    network_mode: host
    depends_on:
      - mktdata
      - mysql

  grafana:
    #image: grafana/grafana:8.2.6
    image: grafana/grafana:8.5.4-ubuntu
    environment:
        GF_PATHS_DATA: '/var/lib/grafana'
    #volumes:
        #- ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
    network_mode: host
    depends_on:
      - mktdata
      - mysql
      - mysql_client

