version: "3"

services:
  mktdata:
    build:
        context: ./
        dockerfile: ./mktdata/Dockerfile
    command: python3 mktdata.py
    #command: python3 ./mktdata/mktdata.py
    ports:
      - 1234:1234

  mysql_client:
    build:
        context: ./
        dockerfile: ./mysql_client/Dockerfile
    command: python3 mysql_client.py
    #command: python3 ./mysql_client/mysql_client.py
    network_mode: host
    depends_on:
      - mktdata

